[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
known_django = "django"
known_third_party = ["rest_framework"]
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.flake8]
exclude = ["venv", ".venv", "__pycache__", "build", "dist"]
max-line-length = 88