# Generated by Django 5.0.7 on 2024-08-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataiq", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chunk",
            name="embedding_size",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="last_update",
        ),
    ]
